### ISSUE TITLE
The code for the pony clone of capture doesn't compile in Pony 0.12.2

### ISSUE THREAD

**Issue by tj800x** [ponylang/inside-the-pony-process-package#1]
I'm new to pony, so I apologize in advance if this issue is mine.

Tom

$ ponyc
Building builtin -> /usr/local/lib/pony/0.12.2-dc26414/packages/builtin
Building . -> /Users/tjohnson/Projects/Pony/inside-the-pony-process-package
Error:
/Users/tjohnson/Projects/Pony/inside-the-pony-process-package/capture.pony:54:42: couldn't find 'cstring' in 'None'
        len = @read[USize](read_end, data.cstring(), size)
                                         ^
Error:
/Users/tjohnson/Projects/Pony/inside-the-pony-process-package/capture.pony:57:15: couldn't find 'truncate' in 'None'
          data.truncate(len)
              ^
Error:
/Users/tjohnson/Projects/Pony/inside-the-pony-process-package/capture.pony:58:15: couldn't find 'push' in 'None'
          data.push(0) // terminate the buffer for String conversion
              ^
Error:
/Users/tjohnson/Projects/Pony/inside-the-pony-process-package/capture.pony:59:44: argument not a subtype of parameter
          _env.out.print(String.from_array(consume data))
                                           ^
    Info:
    /usr/local/lib/pony/0.12.2-dc26414/packages/builtin/array.pony:111:3: None val is not a subtype of Array[U8 val] val
      fun ref undefined[B: (A & Real[B] val & Number) = A](len: USize) =>

**Comment by SeanTAllen** [comment]
@tj800x yeah the code is rather out of date.

**Comment by SeanTAllen** [comment]
@tj800x update pushed. you should be good soon. let me know if you find other issues.

thanks!
